spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  datasource:
    url: jdbc:h2:mem:yonlog;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

yonlog:
  jwt-key: "EAQlPZDkEYeaN50gAoALQPxHBDFEl9ZCxncNNNcnncc="